# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker compose configuration file
version: "3"

services:
  hub:
    image: ghcr.io/mtallenreply/jupyterhub-reply:latest
    container_name: jupyterhub
    restart: always
    networks:
      - jupyterhub-network
    volumes:
      # The JupyterHub configuration file
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      # hier wenn PODMAN_SOCKET vorhanden dann wird es genutzt sonst der fixe wert
#      - "${PODMAN_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock:rw" #this line results to an error
      - "/var/run/docker.sock:/var/run/docker.sock:rw"

      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub-data:/data"
      - "jupyterhub-shared-data:/data/work/shared"
    ports:
      - "8000:8000"
    environment:
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: admin
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
#      DOCKER_NOTEBOOK_IMAGE: quay.io/jupyter/base-notebook:latest
      DOCKER_NOTEBOOK_IMAGE: ghcr.io/mtallenreply/notebook-reply:latest
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
volumes:
  jupyterhub-data:
  jupyterhub-shared-data:   # <<< Shared Volume für alle Container


networks:
  jupyterhub-network:
    name: jupyterhub-network
